# Generated by Django 5.2 on 2025-04-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_remove_place_address_remove_place_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="places.place",
            ),
        ),
    ]
