# Generated by Django 5.2 on 2025-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_review_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="has_comfortable_exits",
            field=models.BooleanField(default=False),
        ),
    ]
