# Generated by Django 5.2 on 2025-04-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_place_has_comfortable_exits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="has_comfortable_exits",
            new_name="has_comfortable_exit",
        ),
    ]
